### ISSUE TITLE
Cannot find module /Instantiator in Heroku server

### ISSUE THREAD

**Issue by jlopezxs** [dacarley/simple-di#4]
In the module index line 5 you have:
`var Instantiator = require("./Instantiator");`
but the filename is instantiator.js

The require use Camelcase and the file is in lowercase, in Linux servers this can crash.

`2016-07-21T15:13:33.742301+00:00 app[web.1]: Error: Cannot find module './Instantiator'
2016-07-21T15:13:33.742321+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-07-21T15:13:33.742321+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-07-21T15:13:33.742322+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-07-21T15:13:33.742323+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/simple-di/index.js:5:20)`

**Comment by blanxii** [comment]
+1

**Comment by dacarley** [comment]
Thanks for the report!

I just released v1.1.1, which fixes this.
